RHYME_LIST = [
         (0, "random"),
         (1, "UW1 (blue, do, you, too, true)"),
         (2, "IY1 (me, see, be, free, agree)"),
         (3, "EY1 (away, say, way, day, okay)"),
         (4, "OW1 (slow, grow, know, joe, go)"),
         (5, "AY1T (night, fight, right, light, tonight)"),
         (6, "AY1 (tie, goodbye, guy, high, sky)"),
         (7, "AH1V (love, above, glove, dove, of)"),
         (8, "AO1R (more, door, before, floor, for)"),
         (9, "IH1T (it, shit, hit, quit, fit)"),
         (10, "AW1N (down, town, clown, downtown, crown)"),
         (11, "AH1N (fun, one, sun, done, run)"),
         (12, "EH1R (care, there, chair, air, beware)"),
         (13, "EH1N (again, then, men, ten, den)"),
         (14, "AY1M (time, rhyme, i'm, crime, climb)"),
         (15, "AY1D (ride, wide, pride, side, cried)"),
         (16, "AW1 (now, how, cow, yow, allow)"),
         (17, "AO1NG (strong, song, kong, wrong, along)"),
         (18, "AY1ND (mind, entwined, find, signed, wind)"),
         (19, "AO1L (fall, wall, small, call, all)"),
         (20, "AA1RT (start, heart, apart, part, hart)"),
         (21, "AY1N (mine, fine, nine, line, shine)"),
         (22, "AW1ND (sound, ground, bound, round, found)"),
         (23, "AY1Z (eyes, guys, size, cries, wise)"),
         (24, "EY1BIY0 (baby, maybe)"),
         (25, "OW1N (alone, bone, own, grown, stone)"),
         (26, "EY1N (rain, pane, plain, insane, remain)"),
         (27, "AE1 (yeah, pah)"),
         (28, "EH1D (dead, bed, instead, said, read)"),
         (29, "EY1M (shame, blame, same, name, dame)"),
         (30, "AA1N (on, upon, c'mon, iran, john)"),
]
