RHYME_LIST = [
        "",
        "UW1 (blue, do, you, too, true)",
		"IY1 (me, see, be, free, agree)",
		"EY1 (away, say, way, day, okay)",
		"OW1 (slow, grow, know, joe, go)",
		"AY1T (night, fight, right, light, tonight)",
		"AY1 (tie, goodbye, guy, high, sky)",
		"AH1V (love, above, glove, dove, of)",
		"AO1R (more, door, before, floor, for)",
		"IH1T (it, shit, hit, quit, fit)",
		"AW1N (down, town, clown, downtown, crown)",
		"AH1N (fun, one, sun, done, run)",
		"EH1R (care, there, chair, air, beware)",
		"EH1N (again, then, men, ten, den)",
		"AY1M (time, rhyme, i'm, crime, climb)",
		"AY1D (ride, wide, pride, side, cried)",
		"AW1 (now, how, cow, yow, allow)",
		"AO1NG (strong, song, kong, wrong, along)",
		"AY1ND (mind, entwined, find, signed, wind)",
		"AO1L (fall, wall, small, call, all)",
		"AA1RT (start, heart, apart, part, hart)",
		"AY1N (mine, fine, nine, line, shine)",
		"AW1ND (sound, ground, bound, round, found)",
		"AY1Z (eyes, guys, size, cries, wise)",
		"EY1BIY0 (baby, maybe)",
		"OW1N (alone, bone, own, grown, stone)",
		"EY1N (rain, pane, plain, insane, remain)",
		"AE1 (yeah, pah)",
		"EH1D (dead, bed, instead, said, read)",
		"EY1M (shame, blame, same, name, dame)",
		"AA1N (on, upon, c'mon, iran, john)",
]
